export const url = "http://localhost:3000"
// export const url = "https://musicspaces.vercel.app"
// export const url = "https://musicspaces-git-feat-multiplayer-jmurphy5613.vercel.app"
// export const apiURL = "https://musicspaces-backend-production.up.railway.app"
export const apiURL = "http://localhost:3001"
